simpletodo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tasks', views.TasksView.as_view(), name='tasks'),
    path('create', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', views.TaskEditView.as_view(), name='edit'),
    path('<int:todo_id>/delete/', views.task_delete, name='delete'),
    path('<int:todo_id>/done/', views.task_done, name='done'),
    path('signup', views.SineUpView.as_view(), name='signup'),
    path('signin', views.SignInView.as_view(), name='signin'),
    path('signout', views.SignOutView.as_view(), name='signout'),

]

todo/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db import models
from django import forms

# Create your models here.
class ToDoUser(AbstractUser):
    pass

class Task(models.Model):
    STATE_CHOICES = {
        ("ToDo", "ToDo"),
        ("Done", "Done"),
    }

    user_id = models.ForeignKey(ToDoUser, on_delete=models.CASCADE)
    state = models.CharField(
        max_length = 4,
        choices    = STATE_CHOICES,
        default = "ToDo",
    )
    task = models.CharField(max_length=200)
    deadline = models.DateTimeField('deadline')
    

    def __str__(self):
        return self.task

    def state_is_done(self):
        """
        stateがdone
        """
        return self.state == "Done"
    
    def state_is_todo(self):
        """
        stateがtodo
        """
        return self.state == "ToDo"

    def deadline_exceeded(self):
        """
        deadline（締切）が超過した
        """
        return self.deadline < timezone.now()
    
    def deadline_approaching(self):
        """
        deadline（締切）が近い（後1日で締め切り）
        """
        near_deadline = self.deadline - datetime.timedelta(days=1)
        return near_deadline < timezone.now() < self.deadline


    

todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
import bootstrap_datepicker_plus as datetimepicker
from .models import Task, ToDoUser

class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = ('state','task', 'deadline', )
        widgets = {
            'state': forms.RadioSelect(
                # attrs={
                #     "class":"form-check-input",
                # }
            ),
            'task': forms.TextInput(
                attrs={
                    'placeholder':'課題を終わらせる',
                    'class':"form-control",
                }
            ),
            # 'deadline': forms.DateTimeInput(
            #     attrs={
            #         'placeholder':'2020-05-26 17:45',
            #         'class':"form-control"
            #     },
            # ),
            'deadline': datetimepicker.DateTimePickerInput(
                format='%Y-%m-%d %H:%M:%S',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                }
            )
        }

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
        self.fields['username'].label = 'Username'
        self.fields['password'].label = 'Password'
    class Meta:
        model = ToDoUser
        fields = ('username', 'password')
        labels = {
            'username':'Username',
            'password':'Password',
        }

class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
        self.fields['username'].label = 'Username'
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Password（確認用）'
    class Meta:
        model = ToDoUser
        fields = ('username', 'password1', 'password2')

todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from django.db.models import F
from django.utils import timezone
from .models import Task, ToDoUser
from .forms import TaskForm, SignUpForm, LoginForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

# Create your views here.
class IndexView(generic.TemplateView):
    template_name ='todo/index.html'
    context_object_name= 'latest_todo_list'

class TasksView(LoginRequiredMixin, generic.ListView):
    template_name ='todo/tasks.html'
    context_object_name= 'latest_todo_list'
    def get_queryset(self):
        user = self.request.user
        return sorted(Task.objects.filter(user_id=user.id).order_by('deadline'), key=lambda task: not task.state_is_done(), reverse=True)

class TaskEditView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('todo:tasks')
    def form_valid(self, form):
        form.instance.user_id = self.request.user
        result = super().form_valid(form)
        return result
    
    def form_invalid(self, form):
        return super().form_invalid(form)

class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name ='todo/task_form.html'
    success_url = reverse_lazy('todo:tasks')
    def form_valid(self, form):
        form.instance.user_id = self.request.user
        result = super().form_valid(form)
        return result
    
    def form_invalid(self, form):
        return super().form_invalid(form)

@login_required
def task_done(request, todo_id):
    task = get_object_or_404(Task, pk=todo_id)
    task.state = "Done"
    task.save()
    return HttpResponseRedirect(reverse('todo:tasks',args=()))

@login_required
def task_delete(request, todo_id):
    task = get_object_or_404(Task, pk=todo_id)
    task.delete()
    return HttpResponseRedirect(reverse('todo:tasks',args=()))


class SignInView(LoginView):
    form_class = LoginForm
    template_name = 'todo/signin.html'

class SignOutView(LogoutView):
    template_name = 'index.html'

class SineUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'todo/signup.html', {
           "input_error_text": False,
           "form": form,
        })

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password1 = form.cleaned_data["password1"]
            password2 = form.cleaned_data["password2"]
            if password1 == password2:
                ToDoUser.objects.create_user(username=username, password=password1)
                user = authenticate(request, username=username, password=password1)
                login(request, user)
                return render(request, 'todo/signup_ok.html', { })
        return render(request, 'todo/signup.html', {
            "input_error_text": True,
            "form": form
        })

todo/templates/todo/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'todo/base/base.css' %}">
    <title>Simple ToDo</title>
</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a href="{% url 'todo:index' %}" class="navbar-brand">Simple Todo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'todo:index' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'todo:tasks' %}">MyPage</a>
                    </li>
                </ul>

                {% if user.is_authenticated %}
                    <span class="navbar-text">Welcome, {{user.get_username}}!</span>  
                    <ul class="navbar-nav">       
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'todo:signout' %}">SignOut<span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'todo:signin' %}">SignIn<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'todo:signup' %}">SignUp<span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                {% endif %}
                
            </div>
        </nav>
    </header>
    {% block main %}
    {% endblock %}
    <footer class="fixed-bottom">
        <nav class="navbar navbar-dark bg-dark justify-content-end">
            <span class="navbar-text">© Howakuro 2020</span>
        </nav>
    </footer>
</body>
</html>

todo/templates/todo/index.html
{% extends "todo/base.html" %}
{% load static %}

{% block main %}
<main>
    <div class="jumbotron jumbotron-fluid text-center">
        <h1 class="display-1">Simple Todo</h1>
        <h3>余計な機能はいらない.</h3>
        <h3>Simple is Best.</h3>
    </div>
    <figure class="text-center">
        <img class="img-fluid" src="{% static 'todo/index/taskmenu.png' %}" alt="">
    </figure>
</main>
{% endblock  %}

todo/templates/todo/signin.html
{% extends "todo/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block main %}
<main>
    <div class="container">
        <h1 class="m-3"><b>Sign In</b></h1>
        <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            <div class="border border-secondary rounded p-5" style="border-width:5px">
                {{ form }}
                <div class="form-group" style="padding:20px 0">
                    <input type="submit" value="Signin" class="btn btn-primary"/>
                </div>
            </div>
        </form>
        
    </div>
</main>

{% endblock  %}

todo/templates/todo/signup.html
{% extends "todo/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block main %}
<main> 
    <div class="container">
        <h1 class="m-3"><b>Sign Up</b></h1>
        <form method="post" enctype="multipart/form-data" action="{% url 'todo:signup' %}">
            {% csrf_token %}
            <div class="border border-secondary rounded p-5" style="">
                {% for f in form%}
                    <div class="form-group">
                        {% if f.errors %}
                        <div class="text-danger">{{ f.errors }}</div>
                        {% endif %}
                        {{ f.label }} {{ f|add_class:"form-control"}}
                        {% if f.help_text %}
                        <p class="help">{{ f.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="form-group" style="padding:20px 0">
                    <input type="submit" value="Create" class="btn btn-primary"/>
                </div>
            </div>
        </form>
        
    </div>
</main>

{% endblock %}

todo/templates/todo/signup_ok.html
{% extends "todo/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block main %}
<main>
    <div class="container">
        <h1 class="m-3"><b>SignUp Success!!</b></h1>
        <p>ユーザー登録に成功しました。</p>
        <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo:tasks' %}'">MyPage</button>
    </div>
</main>

{% endblock  %}

todo/templates/todo/task_form.html
{% extends "todo/base.html" %}
{% load static %}
{% block main %}
    <main>
        <div class="container">
                {% if not form.instance.pk %}
                    <h1 class="m-3"><b>Append Task</b></h3>
                {% else %}
                    <h1 class="m-3"><b>Edit Task</b></h3>
                {% endif %}
                <form method="post" enctype="multipart/form-data" action="">
                    {% csrf_token %}
                    <div class="border border-secondary rounded p-5" style="">
                        <div class="state">
                            <label for="{{ form.state.id_for_label }}">State:</label>
                            {{ form.state.errors}}
                            {{ form.state }}
                        </div>
                        <div class="task py-3">
                            {{ form.state.errors}}
                            <label for="{{ form.task.id_for_label }}">Task:</label>
                            {{ form.task }}
                        </div>    
                        <div class="deadline py-3">
                            {{ form.deadline.errors }}
                            <label for="{{ form.deadline.id_for_label }}">Limit:</label>
                            {{ form.deadline }}
                            {{ form.media }}
                            <ul>
                                <li>右のカレンダーボタンよりGUI入力が可能です。</li>
                                <li>Limitの日付や時間が1桁である場合は必ず先頭に0埋めをしてください。</li>
                                <li>例：2020年1月1日 1時1分 → 2020-01-01 01:01</li>
                            </ul>
                        </div>
                        <div class="form-group" style="padding:20px 0">
                            {% if not form %}
                                <input type="submit" value="Append" class="btn btn-primary"/>
                            {% else %}
                                <input type="submit" value="Edit" class="btn btn-primary"/>
                            {% endif %}
                        </div>
                    </div>
                </form>
        </div>
        <link rel="stylesheet" href="{% static 'task_form/task_form.css' %}">
        <script src="{% static 'task_form/task_form.js' %}"></script>
    </main>
{% endblock %}

todo/templates/todo/tasks.html
{% extends "todo/base.html" %}
{% load static %}
{% block main %}
    <main>
        <div class="container">
            <h1 class="m-3"><b>ToDo List</b></h3>
            <table class="table table-hover" style="table-layout:fixed;">
                <thead class="thead-light ">
                    <tr><th>Task</th><th>State</th><th>Limit</th><th></th></tr>
                </thead>
                {% for todo in latest_todo_list %}
                    {% if todo.deadline_approaching and not todo.state_is_done %}
                        <tr class="table-warning">
                    {% elif todo.deadline_exceeded and not todo.state_is_done %}
                        <tr class="table-danger">
                    {% elif todo.state_is_done%}
                        <tr class="table-success">
                    {% else %}
                        <tr>
                    {% endif %}
                            <td>{{ todo.task }}</td>
                            <td>{{ todo.state }}</td>
                            <td>{{ todo.deadline|date:"Y/m/d H:i"}}</td>
                            <td>
                                <div class="float-right">
                                    {% if not todo.state_is_done %}
                                    <form class="d-inline" method="post" action="{% url 'todo:done' todo.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success rounded-circle mx-2">
                                            <span class="material-icons">done</span>
                                        </button>
                                    </form>
                                    {% endif %}
                                    <form class="d-inline" method="get" action="{% url 'todo:edit' todo.id%}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-info rounded-circle mx-2">
                                            <span class="material-icons">edit</span>
                                        </button>
                                    </form>
                                    <div class="d-inline">
                                        <button type="submit" class="btn btn-danger rounded-circle mx-2" data-toggle="modal" data-target="#modal{{ todo.id }}">
                                            <span class="material-icons">delete_forever</span>
                                        </button>
                                        <div class="modal fade" id="modal{{ todo.id }}" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="label1">Delete Task</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    タスクを削除してよろしいですか？
                                                </div>
                                                <div class="modal-footer">
                                                    <form class="d-inline" method="post" action="{% url "todo:delete" todo.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-secondary">OK</button>
                                                    </form>
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
            </table>
            {% if latest_todo_list%}
                <div class="float-right">
                    <button type="button" class="btn btn-danger rounded-circle pull-right" onclick="location.href='{% url "todo:create" %}'">
                        <span class="material-icons">add</span>
                    </button>
                </div>
            {% else %}
                <div class="float-left">
                    <button type="button" class="btn btn-danger rounded-circle pull-right" onclick="location.href='{% url "todo:create" %}'">
                        <span class="material-icons">add</span>
                    </button>
                </div>
            {% endif %}
        </div>
    </main>
    <link rel="stylesheet" href="{% static 'todo/tasks/tasks.css' %}">
{% endblock %}